# Generated by Django 4.0 on 2025-10-28 00:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='タグ名')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('comment', models.TextField(blank=True, verbose_name='詳細コメント')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='写真')),
                ('latitude', models.FloatField(verbose_name='緯度')),
                ('longitude', models.FloatField(verbose_name='経度')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='地名')),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('is_approved', models.BooleanField(default=False, verbose_name='承認済み')),
                ('tags', models.ManyToManyField(related_name='photo_posts', to='main.Tag', verbose_name='カテゴリ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='投稿ユーザー')),
            ],
            options={
                'verbose_name': '写真投稿',
                'verbose_name_plural': '写真投稿',
                'ordering': ['-posted_at'],
            },
        ),
    ]
