# Generated by Django 4.0 on 2025-10-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopost',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='photopost',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='管理者メモ/対応内容'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='対応優先順位'),
        ),
        migrations.AddField(
            model_name='photopost',
            name='status',
            field=models.CharField(choices=[('new', '新規'), ('in_progress', '対応中'), ('completed', '対応完了'), ('not_required', '対応不可')], default='new', max_length=20, verbose_name='対応状況'),
        ),
    ]
