# Generated by Django 4.0 on 2025-10-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_photopost_is_approved_photopost_admin_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='タイトル'),
        ),
    ]
